ALTER TABLE resposta_aluno ADD COLUMN fk_id_revisor BIGINT;
ALTER TABLE resposta_aluno ADD COLUMN data_revisao TIMESTAMP WITH TIME ZONE;
ALTER TABLE resposta_aluno ADD COLUMN justificativa_revisao TEXT;
ALTER TABLE resposta_aluno ADD COLUMN versao_revisao BIGINT NOT NULL DEFAULT 0;

ALTER TABLE resposta_aluno
    ADD CONSTRAINT fk_resposta_revisor
    FOREIGN KEY (fk_id_revisor) REFERENCES usuario (id);

ALTER TABLE resposta_aluno
    ADD CONSTRAINT ck_resposta_revisao_completa
    CHECK (
        (fk_id_revisor IS NULL
            AND data_revisao IS NULL
            AND justificativa_revisao IS NULL
            AND versao_revisao = 0)
        OR
        (fk_id_revisor IS NOT NULL
            AND data_revisao IS NOT NULL
            AND justificativa_revisao IS NOT NULL
            AND versao_revisao > 0)
    );

CREATE TABLE revisao_resposta_aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_resposta BIGINT NOT NULL,
    fk_id_revisor BIGINT NOT NULL,
    correta BOOLEAN NOT NULL,
    justificativa TEXT NOT NULL,
    data_revisao TIMESTAMP WITH TIME ZONE NOT NULL,
    versao_revisao BIGINT NOT NULL,
    CONSTRAINT fk_revisao_resposta
        FOREIGN KEY (fk_id_resposta) REFERENCES resposta_aluno (id),
    CONSTRAINT fk_revisao_revisor
        FOREIGN KEY (fk_id_revisor) REFERENCES usuario (id),
    CONSTRAINT uk_revisao_resposta_versao
        UNIQUE (fk_id_resposta, versao_revisao),
    CONSTRAINT ck_revisao_versao_positiva
        CHECK (versao_revisao > 0)
);

CREATE INDEX idx_revisao_resposta_data
    ON revisao_resposta_aluno (fk_id_resposta, data_revisao DESC);
