CREATE TABLE auditoria_geracao_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_caso BIGINT NOT NULL,
    fk_id_usuario BIGINT NOT NULL,
    operacao VARCHAR(30) NOT NULL,
    provedor VARCHAR(150) NOT NULL,
    modelo VARCHAR(150) NOT NULL,
    versao_prompt VARCHAR(40) NOT NULL,
    hash_contexto VARCHAR(64) NOT NULL,
    hash_saida VARCHAR(64) NOT NULL,
    referencia_resultado TEXT NOT NULL,
    quantidade_itens INTEGER NOT NULL,
    dados_desidentificados_confirmados BOOLEAN NOT NULL,
    data_geracao TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_auditoria_ia_caso
        FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso),
    CONSTRAINT fk_auditoria_ia_usuario
        FOREIGN KEY (fk_id_usuario) REFERENCES usuario (id),
    CONSTRAINT ck_auditoria_ia_operacao
        CHECK (operacao IN ('GERAR_CASO', 'AJUSTAR_CASO', 'GERAR_PERGUNTAS')),
    CONSTRAINT ck_auditoria_ia_quantidade
        CHECK (quantidade_itens > 0),
    CONSTRAINT ck_auditoria_ia_confirmacao
        CHECK (dados_desidentificados_confirmados = TRUE)
);

CREATE INDEX idx_auditoria_ia_caso_data
    ON auditoria_geracao_ia (fk_id_caso, data_geracao DESC);
