CREATE TABLE solicitacao_geracao_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_usuario BIGINT NOT NULL,
    fk_id_caso BIGINT NOT NULL,
    operacao VARCHAR(30) NOT NULL,
    chave_idempotencia VARCHAR(64) NOT NULL,
    hash_requisicao VARCHAR(64) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    status_resposta INTEGER,
    resposta_serializada TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_solicitacao_ia_usuario
        FOREIGN KEY (fk_id_usuario) REFERENCES usuario (id),
    CONSTRAINT uq_solicitacao_ia_usuario_chave
        UNIQUE (fk_id_usuario, chave_idempotencia),
    CONSTRAINT ck_solicitacao_ia_operacao
        CHECK (operacao IN ('GERAR_CASO', 'AJUSTAR_CASO', 'GERAR_PERGUNTAS')),
    CONSTRAINT ck_solicitacao_ia_estado
        CHECK (estado IN ('EM_ANDAMENTO', 'CONCLUIDA', 'FALHOU')),
    CONSTRAINT ck_solicitacao_ia_concluida
        CHECK (estado <> 'CONCLUIDA' OR (status_resposta IS NOT NULL AND resposta_serializada IS NOT NULL))
);
