CREATE TABLE aluno (
    id_aluno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    curso VARCHAR(255),
    periodo VARCHAR(255)
);

CREATE TABLE professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    materia VARCHAR(255)
);

CREATE TABLE casos_clinicos (
    id_caso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_professor BIGINT,
    titulo VARCHAR(255),
    dificuldade VARCHAR(255),
    disciplina VARCHAR(255),
    area_saude VARCHAR(255),
    estilo VARCHAR(255),
    especialidade VARCHAR(255),
    status VARCHAR(255),
    data_criacao TIMESTAMP,
    data_atualizacao TIMESTAMP,
    objetivo_aprendizagem VARCHAR(255),
    nivel_dificuldade VARCHAR(255),
    CONSTRAINT fk_caso_professor FOREIGN KEY (fk_id_professor) REFERENCES professor (id)
);

CREATE TABLE paciente (
    id_paciente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_caso BIGINT,
    nome VARCHAR(255),
    profissao VARCHAR(255),
    sexo VARCHAR(255),
    idade INTEGER,
    estado_civil VARCHAR(255),
    altura VARCHAR(255),
    peso VARCHAR(255),
    CONSTRAINT fk_paciente_caso FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso)
);

CREATE TABLE conteudo_clinico (
    id_conteudo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_caso BIGINT,
    sintomas VARCHAR(255),
    contexto VARCHAR(255),
    exam_clinico VARCHAR(255),
    antec_clinico VARCHAR(255),
    diag_esperado VARCHAR(255),
    CONSTRAINT fk_conteudo_caso FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso)
);

CREATE TABLE pergunta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_caso BIGINT,
    texto VARCHAR(255),
    alternativa_a VARCHAR(255),
    alternativa_b VARCHAR(255),
    alternativa_c VARCHAR(255),
    alternativa_d VARCHAR(255),
    alternativa_e VARCHAR(255),
    resposta VARCHAR(255),
    tipo VARCHAR(255),
    gabarito VARCHAR(255),
    tempo_esperado VARCHAR(255),
    CONSTRAINT fk_pergunta_caso FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso)
);

CREATE TABLE resposta_aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_aluno BIGINT,
    fk_id_caso BIGINT,
    fk_id_pergunta BIGINT,
    resposta_marcada VARCHAR(255),
    correta BOOLEAN,
    data_resposta TIMESTAMP,
    CONSTRAINT fk_resposta_aluno FOREIGN KEY (fk_id_aluno) REFERENCES aluno (id_aluno),
    CONSTRAINT fk_resposta_caso FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso),
    CONSTRAINT fk_resposta_pergunta FOREIGN KEY (fk_id_pergunta) REFERENCES pergunta (id)
);
