CREATE TABLE alternativa_pergunta (
    id_alternativa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_pergunta BIGINT NOT NULL,
    letra VARCHAR(255),
    texto VARCHAR(255),
    correta BOOLEAN,
    CONSTRAINT fk_alternativa_pergunta FOREIGN KEY (fk_id_pergunta) REFERENCES pergunta (id)
);
