ALTER TABLE casos_clinicos
    ADD COLUMN tempo_limite_minutos INTEGER NOT NULL DEFAULT 60;

ALTER TABLE casos_clinicos
    ADD CONSTRAINT ck_caso_tempo_limite
    CHECK (tempo_limite_minutos BETWEEN 15 AND 480);

ALTER TABLE pergunta DROP COLUMN tempo_esperado;

CREATE TABLE tentativa_caso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_id_aluno BIGINT NOT NULL,
    fk_id_caso BIGINT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_limite TIMESTAMP WITH TIME ZONE NOT NULL,
    data_finalizacao TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_tentativa_aluno
        FOREIGN KEY (fk_id_aluno) REFERENCES aluno (id_aluno),
    CONSTRAINT fk_tentativa_caso
        FOREIGN KEY (fk_id_caso) REFERENCES casos_clinicos (id_caso),
    CONSTRAINT uk_tentativa_aluno_caso
        UNIQUE (fk_id_aluno, fk_id_caso),
    CONSTRAINT ck_tentativa_datas
        CHECK (data_limite > data_inicio),
    CONSTRAINT ck_tentativa_finalizacao
        CHECK (data_finalizacao IS NULL OR data_finalizacao >= data_inicio)
);

CREATE INDEX idx_tentativa_caso_aluno ON tentativa_caso (fk_id_aluno);
CREATE INDEX idx_tentativa_caso_prazo ON tentativa_caso (data_limite);
